# Generated by Django 4.2.7 on 2023-11-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_userprofile_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="total_reports",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="total_tradelines",
            field=models.IntegerField(default=0),
        ),
    ]
