"""
Django settings for sendesta project.

Generated by 'django-admin startproject' using Django 3.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import django_heroku
import dj_database_url
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "aydh87oayd7ahsd87qwhdqyd82d-ad=q-d=qisduh87qydua!z+n)000yxhr=3+k*a^a)q8y=)em_%l#pff0jt0#z+=b$qf0"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

LOGIN_URL = "/account/"

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # downloaded packages
    # pip install django-import-export
    'import_export',
    # pip install fuzzywuzzy
    'fuzzywuzzy',
    # custom apps
    "bankapp",
    "users",
    "dashboard",
    "sendesta",
    "rest_framework",
    "credit_scoring",
    'crispy_forms',
    'crispy_bootstrap4',
]

REST_FRAMEWORK = {
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],
}

CRISPY_TEMPLATE_PACK = 'bootstrap4'
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "sendesta.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "sendesta.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases
# The credentials will change occasionally in Heroku and will need updated
# Can be found in Resources > Click Heroku Postgres Add-on 

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # Use SQLite engine
        'NAME': BASE_DIR / 'db.sqlite3',  # Database file will be created in the base directory
    }
}



# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = "/static/"

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"



# live
# STRIPE_SECRET_KEY = "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"
# STRIPE_PUBLISHABLE_KEY = "pk_live_51NL8jGCXMn20P5iNNrUILc55jOvJNiXR4EELtrgHo1SvjuM1z3vv7Lf4R6d1LKyQ3igocEKgHN4rDqRQzTzw225800hS19S6b2"
# STRIPE_ENDPOINT_SECRET = "whsec_5r9pKDYZGqZbYHvOogIMID51yOnQqKoi"

# test
# STRIPE_SECRET_KEY = "sk_test_51NL8jGCXMn20P5iNW5zm9m8HDAlAsshXhYLaDT7RRQk3pT8V1buOZbmx0Chbt7Eq454cWZPuSU49aNmB6X1NwH5m00EaqPm1Aq"
# STRIPE_PUBLISHABLE_KEY = "pk_test_51NL8jGCXMn20P5iNNqF4oEH8BURHqCdfJpUb1Rc07krcshAwU526wtYf8gK6cHFsB6RoOxh5XvsD1UymE94tJmAk00CMblgNZz"

#test for credit report
STRIPE_PUBLISHABLE_KEY = 'pk_live_51PZPSLRo60QijuQnP2NAUnZ1WnvmYJsKvA4UECc3RZq2OD7LWbwN3N74qwXwKwXJlhqwAPWZiTIrpR2R0OxSs7ML00ix4zgYE0'
STRIPE_SECRET_KEY = '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'
STRIPE_PRICE_ID = 'price_1PdYG7Ro60QijuQn0v0awnDt'

# STRIPE_SECRET_KEY = "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"
# STRIPE_PUBLISHABLE_KEY = "pk_live_51NL8jGCXMn20P5iNNrUILc55jOvJNiXR4EELtrgHo1SvjuM1z3vv7Lf4R6d1LKyQ3igocEKgHN4rDqRQzTzw225800hS19S6b2"

# my keys
# STRIPE_SECRET_KEY = "sk_test_51LMQp6EbZM91ZLdPkJJbwaclFyft6hNrvLdoD8Sbv71cYaESLRe7km5QmPMk0QLUWRsLDvNDRLo0MO7rqP0roKCn00kd4PNVqB"
# STRIPE_PUBLISHABLE_KEY = "pk_test_51LMQp6EbZM91ZLdPeHiF40bIZzOLGU3XtJIatnwPECZIA7B6z1FtT5mKMrJUE6y8eCuwnqzmKafAvjQ2hRgB9c5e00Xj2rspNT"
# STRIPE_ENDPOINT_SECRET = "whsec_317d6bc527d3db1b6e6d40a9a06cbc63851d6c67f0e1176acd1abd5edee8aa67"

# test
# STRIPE_SECRET_KEY = "sk_test_51JXU1sJtDhAmrBJDWJBzAkzWGakzexR7a5iLvsumY5EITEBnhZ1o8vW0dF261997gLKFVMX2EYZ4L3qCud8PXjkR00hhBDOIvB"
# STRIPE_PUBLISHABLE_KEY = "pk_test_51JXU1sJtDhAmrBJDgImxOEb35OhxnTuYSASsfol7xaDFFm2MfgCZOpsICDTgY5le9AdtnJ8JIkugKcCGqtxFJydz00VPli5F8E"
CRISPY_TEMPLATE_PACK = "bootstrap4"

django_heroku.settings(locals())
