# Generated by Django 4.2.7 on 2023-11-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bankapp", "0006_alter_stripecustomer_stripesubscriptionid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stripecustomer",
            name="stripeSubscriptionId",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
