# Generated by Django 4.2.7 on 2023-11-26 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dashboard", "0003_alter_companyinformation_user"),
        ("bankapp", "0007_alter_stripecustomer_stripesubscriptionid"),
    ]

    operations = [
        migrations.CreateModel(
            name="CanDownloadReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_information",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="can_download",
                        to="dashboard.companyinformation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="can_download",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
