# Generated by Django 4.2.7 on 2023-11-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bankapp", "0008_candownloadreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="total_reports",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="plan",
            name="total_tradelines",
            field=models.IntegerField(default=12),
        ),
    ]
