# Generated by Django 3.2.6 on 2023-11-28 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0006_auto_20231126_2315'),
        ('bankapp', '0009_plan_total_reports_plan_total_tradelines'),
    ]

    operations = [
    ]
