# Generated by Django 3.2.6 on 2023-11-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dispute'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinformation',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companyinformation',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
