# Generated by Django 4.2.7 on 2023-11-27 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dashboard", "0004_companyinformation_country_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sendestascore",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maximum_credit_recommendation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="yourcurrenttradelines",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_tradelines",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
