# Generated by Django 3.2.6 on 2023-11-28 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20231126_0307'),
        ('dashboard', '0005_alter_sendestascore_user_and_more'),
    ]

    operations = [
    ]
