# Generated by Django 5.0.6 on 2024-07-03 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_merge_20231128_2225"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyinformation",
            name="city",
        ),
        migrations.RemoveField(
            model_name="companyinformation",
            name="state",
        ),
    ]
